/** Authentication and dashboard  */
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESSFULL = "REGISTER_SUCCESSFULL";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SOCIAL_LOGIN_USER = "SOCIAL_LOGIN_USER";
export const SOCIAL_LOGIN_SUCCESSFULL = "SOCIAL_LOGIN_SUCCESSFULL";
export const SOCIAL_LOGIN_FAIL = "SOCIAL_LOGIN_FAIL";


export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";

export const FORGOTPASSWORD_USER = "FORGOTPASSWORD_USER";
export const FORGOTPASSWORD_SUCCESSFULL = "FORGOTPASSWORD_SUCCESSFULL";
export const FORGOTPASSWORD_FAIL = "FORGOTPASSWORD_FAIL";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESSFULL = "CHANGE_PASSWORD_SUCCESSFULL";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const RESETPASSWORD_USER = "RESETPASSWORD_USER";
export const RESETPASSWORD_SUCCESSFULL = "RESETPASSWORD_SUCCESSFULL";
export const RESETPASSWORD_FAIL = "RESETPASSWORD_FAIL";

export const EDIT_ADMIN_PROFILE = "EDIT_ADMIN_PROFILE";
export const EDIT_ADMIN_PROFILE_SUCCESS = "EDIT_ADMIN_PROFILE_SUCCESS";
export const EDIT_ADMIN_PROFILE_FAIL = "EDIT_ADMIN_PROFILE_FAIL";

export const VALIDATETOKEN_USER = "VALIDATETOKEN_USER";
export const VALIDATETOKEN_SUCCESSFULL = "VALIDATETOKEN_SUCCESSFULL";
export const VALIDATETOKEN_FAIL = "VALIDATETOKEN_FAIL";

export const DASHBOARD = "DASHBOARD";
export const DASHBOARD_SUCCESSFULL = "DASHBOARD_SUCCESSFULL";
export const DASHBOARD_FAIL = "DASHBOARD_FAIL";

/** Action for Category management */
export const GET_MASTER_CATEGORY = "GET_MASTER_CATEGORY";
export const GET_MASTER_CATEGORY_SUCCESS = "GET_MASTER_CATEGORY_SUCCESS";
export const GET_MASTER_CATEGORY_FAIL = "GET_MASTER_CATEGORY_FAIL";
export const LIST_CATEGORY = "LIST_CATEGORY";
export const LIST_CATEGORY_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const LIST_CATEGORY_FAIL = "LIST_CATEGORY_FAIL";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const RESET_CATEGORY_NOTIFICATION = "RESET_CATEGORY_NOTIFICATION";

/** Action for user management */
export const LIST_USER = "LIST_USER";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAIL = "ADD_CATEGORY_FAIL";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const SPECIAL_USER = "SPECIAL_USER";
export const SPECIAL_USER_SUCCESS = "SPECIAL_USER_SUCCESS";
export const SPECIAL_USER_FAIL = "SPECIAL_USER_FAIL";

export const SET_EDIT_USER = "SET_EDIT_USER";

/** Action for company user management */
export const LIST_CUSER = "LIST_CUSER";
export const LIST_CUSER_SUCCESS = "LIST_CUSER_SUCCESS";
export const LIST_CUSER_FAIL = "LIST_CUSER_FAIL";

export const ADD_CUSER = "ADD_CUSER";
export const ADD_CUSER_SUCCESS = "ADD_CUSER_SUCCESS";
export const ADD_CUSER_FAIL = "ADD_CUSER_FAIL";

export const EDIT_CUSER = "EDIT_CUSER";
export const EDIT_CUSER_SUCCESS = "EDIT_CUSER_SUCCESS";
export const EDIT_CUSER_FAIL = "EDIT_CUSER_FAIL";

export const DELETE_CUSER = "DELETE_CUSER";
export const DELETE_CUSER_SUCCESS = "DELETE_CUSER_SUCCESS";
export const DELETE_CUSER_FAIL = "DELETE_CUSER_FAIL";

export const SET_EDIT_CUSER = "SET_EDIT_CUSER";
/** Sub category Management */
export const FETCH_SUBCATEGORY_MANAGEMENT = "FETCH_SUBCATEGORY_MANAGEMENT";
export const FETCH_SUBCATEGORY_MANAGEMENT_SUCCESS = "FETCH_SUBCATEGORY_MANAGEMENT_SUCCESS";
export const FETCH_SUBCATEGORY_MANAGEMENT_FAIL = "FETCH_SUBCATEGORY_MANAGEMENT_FAIL";

export const CHANGE_SUBCATEGORY_STATUS = "CHANGE_SUBCATEGORY_STATUS";
export const CHANGE_SUBCATEGORY_STATUS_SUCCESS = "CHANGE_SUBCATEGORY_STATUS_SUCCESS";
export const CHANGE_SUBCATEGORY_STATUS_FAIL = "CHANGE_SUBCATEGORY_STATUS_FAIL";

export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAIL = "ADD_SUBCATEGORY_FAIL";

export const UPDATE_SUBCATEGORY = "UPDATE_CATEGORY";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
export const RESET_USER_NOTIFICATION = "RESET_USER_NOTIFICATION";
export const RESET_SUBCATEGORY_NOTIFICATION = "RESET_SUBCATEGORY_NOTIFICATION";

/** Action for cms management */
export const LIST_CMS = "LIST_CMS";
export const LIST_CMS_SUCCESS = "LIST_CMS_SUCCESS";
export const LIST_CMS_FAIL = "LIST_CMS_FAIL";

export const EDIT_CMS = "EDIT_CMS";
export const EDIT_CMS_SUCCESS = "EDIT_CMS_SUCCESS";
export const EDIT_CMS_FAIL = "EDIT_CMS_FAIL";

export const SET_EDIT_CMS = "SET_EDIT_CMS";
export const RESET_CMS_NOTIFICATION = "RESET_CMS_NOTIFICATION";



/** Action for video management */
export const LIST_VIDEO = "LIST_VIDEO";
export const LIST_VIDEO_SUCCESS = "LIST_VIDEO_SUCCESS";
export const LIST_VIDEO_FAIL = "ADD_CATEGORY_FAIL";

export const ADD_VIDEO = "ADD_VIDEO";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";
export const ADD_VIDEO_FAIL = "ADD_VIDEO_FAIL";

export const EDIT_VIDEO = "EDIT_VIDEO";
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";
export const EDIT_VIDEO_FAIL = "EDIT_VIDEO_FAIL";

export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";

export const SET_EDIT_VIDEO = "SET_EDIT_VIDEO";
export const RESET_VIDEO_NOTIFICATION = "RESET_VIDEO_NOTIFICATION";

//timeslot
export const GET_TIMESLOT = "GET_TIMESLOT";
export const GET_TIMESLOT_SUCCESSFULL = "GET_TIMESLOT_SUCCESSFULL";
export const GET_TIMESLOT_FAIL = "GET_TIMESLOT_FAIL";

export const CHANGE_TIMESLOT = "CHANGE_TIMESLOT";
export const CHANGE_TIMESLOT_SUCCESSFULL = "CHANGE_TIMESLOT_SUCCESSFULL";
export const CHANGE_TIMESLOT_FAIL = "CHANGE_TIMESLOT_FAIL";

//mock interview
export const LIST_MOCK = "LIST_MOCK";
export const LIST_MOCK_SUCCESS = "LIST_MOCK_SUCCESS";
export const LIST_MOCK_FAIL = "LIST_MOCK_FAIL";

export const UPDATE_MOCK = "UPDATE_MOCK";
export const UPDATE_MOCK_SUCCESS = "UPDATE_MOCK_SUCCESS";
export const UPDATE_MOCK_FAIL = "UPDATE_MOCK_FAIL";

export const RESET_MOCK_NOTIFICATION = "RESET_MOCK_NOTIFICATION";

export const FETCH_CAREER_PATH = "FETCH_CAREER_PATH"
export const FETCH_CAREER_PATH_SUCCESSFULL = "FETCH_CAREER_PATH_SUCCESSFULL"
export const FETCH_CAREER_PATH_FAIL = "FETCH_CAREER_PATH_FAIL"

export const GET_ALL_CITIES = "GET_ALL_CITIES";
export const GET_ALL_CITIES_SUCCESS = "GET_ALL_CITIES_SUCCESS";

export const GET_ALL_SKILLS = "GET_ALL_SKILLS";
export const GET_ALL_SKILLS_SUCCESS = "GET_ALL_SKILLS_SUCCESS";

//report
/** Action for user management */
export const RLIST_USER = "RLIST_USER";
export const RLIST_USER_SUCCESS = "RLIST_USER_SUCCESS";
export const RLIST_USER_FAIL = "RLIST_USER_FAIL";